services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/code
      - .:/workspace

  db:
    image: postgres:latest
    env_file:
      - ./database.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/database

volumes:
  postgres-data:
